YUI.add('loader-demo', function (Y, NAME) {
/* This file is auto-generated by locator plugin express-yui for bundle demo */

/*jshint maxlen:900, eqeqeq: false */

/**
 * YUI 3 module metadata
 * @module loader-demo
 */
YUI.Env[Y.version].modules = YUI.Env[Y.version].modules || {};
Y.mix(YUI.Env[Y.version].modules, {
    "alerts-model": {
        "group": "demo",
        "requires": [
            "model"
        ]
    },
    "binder-index": {
        "affinity": "client",
        "group": "demo",
        "requires": [
            "node",
            "demo-templates-foo"
        ]
    },
    "demo-templates-bar": {
        "group": "demo",
        "requires": [
            "handlebars-base"
        ]
    },
    "demo-templates-foo": {
        "group": "demo",
        "requires": [
            "template-micro"
        ]
    },
    "demo-templates-index": {
        "group": "demo",
        "requires": [
            "handlebars-base"
        ]
    },
    "loader-demo": {
        "affinity": "client",
        "group": "demo"
    }
});
}, '@VERSION@', {"requires": ["loader-base"]});
